# Introducción

Vamos a analizar un conjunto de datos de canciones y sus estadísticas por semanas: `listas_musica.csv`

Es un conjunto de datos que nos permite trabajar los conceptos de `pandas` y `numpy`.

El ejercicio será guiado aunque se permite no ver las soluciones para realizar las tareas.

Las columnas del `dataset` son:

* `date`:	Tipo `date` - Fecha de la lista.
* `rank`:	Tipo `int`	- Posición del ranking de la canción en esa fecha.
* `song`:	Tipo `str`	- Nombre de la canción.
* `artist`:	Tipo `str` - Artista.
* `last-week`:	Tipo `int` -	Posición en el ranking de la semana anterior.
* `peak-rank`: Tipo `int`	- La mejor posición de la canción en el ranking.
* `weeks-on-board`: Tipo `int` -	Número de semanas que la canción lleva en la lista.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Carga de librerías

Cargue las librerías `numpy`, `pandas` y `os`.

In [ ]:
import numpy as np
import pandas as pd

### Solución

# Carga del dataset

Lea el dataset y conviértalo en un `dataframe`.

Imprima el dataset una vez lo tenga.

### Solución

In [ ]:
datos_musica=pd.read_csv("/content/drive/MyDrive/Archivos Colab/PROYECTO 1/listas_musica.csv")
print(datos_musica)

              date  rank                                 song  \
0       2021-11-06     1                           Easy On Me
1       2021-11-06     2                                 Stay
2       2021-11-06     3                        Industry Baby
3       2021-11-06     4                           Fancy Like
4       2021-11-06     5                           Bad Habits
...            ...   ...                                  ...
330082  1958-08-04    96                        Over And Over
330083  1958-08-04    97                     I Believe In You
330084  1958-08-04    98                      Little Serenade
330085  1958-08-04    99  I'll Get By (As Long As I Have You)
330086  1958-08-04   100                                 Judy

                               artist  last-week  peak-rank  weeks-on-board
0                               Adele        1.0          1               3
1       The Kid LAROI & Justin Bieber        2.0          1              16
2             Lil Nas X & Jack Harlow        3.0          1              14
3                        Walker Hayes        4.0          3              19
4                          Ed Sheeran        5.0          2              18
...                               ...        ...        ...             ...
330082                Thurston Harris        NaN         96               1
330083                Robert & Johnny        NaN         97               1
330084              The Ames Brothers        NaN         98               1
330085                 Billy Williams        NaN         99               1
330086                Frankie Vaughan        NaN        100               1

[330087 rows x 7 columns]

In [ ]:
type(datos_musica)

pandas.core.frame.DataFrame

#Limpieza de datos

Rellene con `0` usando `fillna()`.

### Solución

In [ ]:
lista_limpia = datos_musica.fillna(0)
print(lista_limpia)

              date  rank                                 song  \
0       2021-11-06     1                           Easy On Me
1       2021-11-06     2                                 Stay
2       2021-11-06     3                        Industry Baby
3       2021-11-06     4                           Fancy Like
4       2021-11-06     5                           Bad Habits
...            ...   ...                                  ...
330082  1958-08-04    96                        Over And Over
330083  1958-08-04    97                     I Believe In You
330084  1958-08-04    98                      Little Serenade
330085  1958-08-04    99  I'll Get By (As Long As I Have You)
330086  1958-08-04   100                                 Judy

                               artist  last-week  peak-rank  weeks-on-board
0                               Adele        1.0          1               3
1       The Kid LAROI & Justin Bieber        2.0          1              16
2             Lil Nas X & Jack Harlow        3.0          1              14
3                        Walker Hayes        4.0          3              19
4                          Ed Sheeran        5.0          2              18
...                               ...        ...        ...             ...
330082                Thurston Harris        0.0         96               1
330083                Robert & Johnny        0.0         97               1
330084              The Ames Brothers        0.0         98               1
330085                 Billy Williams        0.0         99               1
330086                Frankie Vaughan        0.0        100               1

[330087 rows x 7 columns]

# Imprima algunos valores de ejemplos

Use `tail()` para imprimir algunos valores.

Fíjese en las columnas del dataset.

### Solución

In [ ]:
lista_limpia.tail(100)

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
329987,1958-08-04,1,Poor Little Fool,Ricky Nelson,0.0,1,1
329988,1958-08-04,2,Patricia,Perez Prado And His Orchestra,0.0,2,1
329989,1958-08-04,3,Splish Splash,Bobby Darin,0.0,3,1
329990,1958-08-04,4,Hard Headed Woman,Elvis Presley With The Jordanaires,0.0,4,1
329991,1958-08-04,5,When,Kalin Twins,0.0,5,1
...,...,...,...,...,...,...,...
330082,1958-08-04,96,Over And Over,Thurston Harris,0.0,96,1
330083,1958-08-04,97,I Believe In You,Robert & Johnny,0.0,97,1
330084,1958-08-04,98,Little Serenade,The Ames Brothers,0.0,98,1
330085,1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,0.0,99,1
330086,1958-08-04,100,Judy,Frankie Vaughan,0.0,100,1

# Calcule los top 30 artistas

Puede usar la función `value_counts()` y `head(...)`.

Fíjese en usar la columna correspondiente.

### Solución

In [ ]:
top_10_artistas= lista_limpia["artist"].value_counts().head(10)
print(top_10_artistas)

Taylor Swift     1023
Elton John        889
Madonna           857
Drake             787
Kenny Chesney     769
Tim McGraw        731
Keith Urban       673
Stevie Wonder     659
Rod Stewart       657
Mariah Carey      621
Name: artist, dtype: int64

In [ ]:
top_30_artistas = lista_limpia['artist'].value_counts().head(30)
print(top_30_artistas)

Taylor Swift             1023
Elton John                889
Madonna                   857
Drake                     787
Kenny Chesney             769
Tim McGraw                731
Keith Urban               673
Stevie Wonder             659
Rod Stewart               657
Mariah Carey              621
Michael Jackson           611
Chicago                   607
Rascal Flatts             604
Billy Joel                588
The Rolling Stones        585
The Beatles               585
Jason Aldean              572
Aretha Franklin           569
Rihanna                   566
P!nk                      564
Whitney Houston           561
Brad Paisley              559
Neil Diamond              553
George Strait             553
Luke Bryan                543
Carrie Underwood          541
Daryl Hall John Oates     540
The Beach Boys            531
Toby Keith                526
Bee Gees                  516
Name: artist, dtype: int64

# Muestre el top 15 de canciones junto con su cantante

### Solución

In [ ]:
top_15_canciones=lista_limpia[["artist","song"]].value_counts().head(15)
print(top_15_canciones)

artist                                     song
The Weeknd                                 Blinding Lights                        90
Imagine Dragons                            Radioactive                            87
AWOLNATION                                 Sail                                   79
Jason Mraz                                 I'm Yours                              76
LeAnn Rimes                                How Do I Live                          69
LMFAO Featuring Lauren Bennett & GoonRock  Party Rock Anthem                      68
OneRepublic                                Counting Stars                         68
Jewel                                      Foolish Games/You Were Meant For Me    65
Adele                                      Rolling In The Deep                    65
Carrie Underwood                           Before He Cheats                       64
The Lumineers                              Ho Hey                                 62
Lifehouse                                  You And Me                             62
Gabby Barrett Featuring Charlie Puth       I Hope                                 62
Post Malone                                Circles                                61
Imagine Dragons                            Demons                                 61
dtype: int64

#Muestre el top 10 de los artistas, canciones y su mejor posición

### Solución

In [ ]:
top_10_acmp=lista_limpia[["artist","song","peak-rank"]].value_counts().head(10)
print(top_10_acmp)

artist                                     song                     peak-rank
The Weeknd                                 Blinding Lights          1            74
Ed Sheeran                                 Shape Of You             1            58
Jason Mraz                                 I'm Yours                6            56
LMFAO Featuring Lauren Bennett & GoonRock  Party Rock Anthem        1            54
The Black Eyed Peas                        I Gotta Feeling          1            54
Justin Timberlake                          Can't Stop The Feeling!  1            52
Taylor Swift                               Shake It Off             1            50
The Chainsmokers Featuring Halsey          Closer                   1            50
Post Malone                                Circles                  1            50
Mark Ronson Featuring Bruno Mars           Uptown Funk!             1            49
dtype: int64

# Artistas más reproducidos por semanas

Transforme la columna `date` en `datetime`.

Use  `set_index` para crear un índice en la columna `date`.

Imprima el dataframe con el nuevo índice.

### Solución

In [ ]:
lista_limpia.dtypes

date               object
rank                int64
song               object
artist             object
last-week         float64
peak-rank           int64
weeks-on-board      int64
dtype: object

In [ ]:
lista_limpia['date'] = lista_limpia['date'].apply(pd.to_datetime)
lista_limpia.set_index('date', inplace=True)
lista_limpia.head()

,rank,song,artist,last-week,peak-rank,weeks-on-board
date,,,,,,
2021-11-06,1,Easy On Me,Adele,1.0,1,3
2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18

# Encuentre los más y menos escuchados según un intervalo de tiempo

Puede usar `resample(frecuencia)[columna]`. 

Las frecuencias que puede usar son:
* H - Horaria
* D - Diaria
* W - Semanal
* M - Mensual
* A - Anual

Puede usar `.agg([columnas])` para agregar los datos

### Solución

In [ ]:
lista_limpia.resample('W')['artist'].agg(['first','last'])

                                    first                        last
date
1958-08-10                   Ricky Nelson             Frankie Vaughan
1958-08-17                   Ricky Nelson        The Kirby Stone Four
1958-08-24               Domenico Modugno     Count Basie & His Orch.
1958-08-31                   The Elegants              Eileen Rodgers
1958-09-07               Domenico Modugno                  Jill Corey
...                                   ...                         ...
2021-10-10                 Coldplay x BTS                  Kanye West
2021-10-17  The Kid LAROI & Justin Bieber  YoungBoy Never Broke Again
2021-10-24        Lil Nas X & Jack Harlow  YoungBoy Never Broke Again
2021-10-31                          Adele             Priscilla Block
2021-11-07                          Adele  YoungBoy Never Broke Again

[3301 rows x 2 columns]