# Introducción

Vamos a analizar un conjunto de datos de canciones y sus estadísticas por semanas: `listas_musica.csv`

Es un conjunto de datos que nos permite trabajar los conceptos de `pandas` y `numpy`.

El ejercicio será guiado aunque se permite no ver las soluciones para realizar las tareas.

Las columnas del `dataset` son:

* `date`:	Tipo `date` - Fecha de la lista.
* `rank`:	Tipo `int`	- Posición del ranking de la canción en esa fecha.
* `song`:	Tipo `str`	- Nombre de la canción.
* `artist`:	Tipo `str` - Artista.
* `last-week`:	Tipo `int` -	Posición en el ranking de la semana anterior.
* `peak-rank`: Tipo `int`	- La mejor posición de la canción en el ranking.
* `weeks-on-board`: Tipo `int` -	Número de semanas que la canción lleva en la lista.

# Carga de librerías

Cargue las librerías `numpy`, `pandas` y `os`.

### Solución

In [47]:
import numpy as np
import pandas as pd
import os

# Carga del dataset

Lea el dataset y conviértalo en un `dataframe`.

Imprima el dataset una vez lo tenga.

### Solución

In [72]:
data = pd.read_csv('listas_musica.csv')

#Limpieza de datos

Rellene con `0` usando `fillna()`.

### Solución

In [73]:

data = data.fillna(0)

# Imprima algunos valores de ejemplos

Use `tail()` para imprimir algunos valores.

Fíjese en las columnas del dataset.

### Solución

In [74]:
data.tail()

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
330082,1958-08-04,96,Over And Over,Thurston Harris,0.0,96,1
330083,1958-08-04,97,I Believe In You,Robert & Johnny,0.0,97,1
330084,1958-08-04,98,Little Serenade,The Ames Brothers,0.0,98,1
330085,1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,0.0,99,1
330086,1958-08-04,100,Judy,Frankie Vaughan,0.0,100,1

# Calcule los top 30 artistas

Puede usar la función `value_counts()` y `head(...)`.

Fíjese en usar la columna correspondiente.

### Solución

In [75]:
data['artist'].value_counts().head(30)

Taylor Swift             1023
Elton John                889
Madonna                   857
Drake                     787
Kenny Chesney             769
Tim McGraw                731
Keith Urban               673
Stevie Wonder             659
Rod Stewart               657
Mariah Carey              621
Michael Jackson           611
Chicago                   607
Rascal Flatts             604
Billy Joel                588
The Rolling Stones        585
The Beatles               585
Jason Aldean              572
Aretha Franklin           569
Rihanna                   566
P!nk                      564
Whitney Houston           561
Brad Paisley              559
Neil Diamond              553
George Strait             553
Luke Bryan                543
Carrie Underwood          541
Daryl Hall John Oates     540
The Beach Boys            531
Toby Keith                526
Bee Gees                  516
Name: artist, dtype: int64

# Muestre el top 15 de canciones junto con su cantante

### Solución

In [76]:
data.loc[:,['song','artist']].head(15)

                       song                                 artist
0                Easy On Me                                  Adele
1                      Stay          The Kid LAROI & Justin Bieber
2             Industry Baby                Lil Nas X & Jack Harlow
3                Fancy Like                           Walker Hayes
4                Bad Habits                             Ed Sheeran
5                Way 2 Sexy    Drake Featuring Future & Young Thug
6                   Shivers                             Ed Sheeran
7                  Good 4 U                         Olivia Rodrigo
8              Need To Know                               Doja Cat
9                Levitating                               Dua Lipa
10                  Essence  Wizkid Featuring Justin Bieber & Tems
11             Kiss Me More                 Doja Cat Featuring SZA
12               Heat Waves                          Glass Animals
13                  Beggin'                               Maneskin
14  Cold Heart (PNAU Remix)                  Elton John & Dua Lipa

#Muestre el top 10 de los artistas, canciones y su mejor posición

### Solución

In [77]:
data.loc[:,['song','artist', "peak-rank"]].value_counts().head(10)

song                     artist                                     peak-rank
Blinding Lights          The Weeknd                                 1            74
Shape Of You             Ed Sheeran                                 1            58
I'm Yours                Jason Mraz                                 6            56
I Gotta Feeling          The Black Eyed Peas                        1            54
Party Rock Anthem        LMFAO Featuring Lauren Bennett & GoonRock  1            54
Can't Stop The Feeling!  Justin Timberlake                          1            52
Shake It Off             Taylor Swift                               1            50
Closer                   The Chainsmokers Featuring Halsey          1            50
Circles                  Post Malone                                1            50
Uptown Funk!             Mark Ronson Featuring Bruno Mars           1            49
dtype: int64

# Artistas más reproducidos por semanas

Transforme la columna `date` en `datetime`.

Use  `set_index` para crear un índice en la columna `date`.

Imprima el dataframe con el nuevo índice.

### Solución

In [78]:
data['date'] = data['date'].apply(pd.to_datetime)
data.set_index('date', inplace=True)

In [79]:
data

,rank,song,artist,last-week,peak-rank,weeks-on-board
date,,,,,,
2021-11-06,1,Easy On Me,Adele,1.0,1,3
2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18
...,...,...,...,...,...,...
1958-08-04,96,Over And Over,Thurston Harris,0.0,96,1
1958-08-04,97,I Believe In You,Robert & Johnny,0.0,97,1
1958-08-04,98,Little Serenade,The Ames Brothers,0.0,98,1
1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,0.0,99,1
1958-08-04,100,Judy,Frankie Vaughan,0.0,100,1

# Encuentre los más y menos escuchados según un intervalo de tiempo

Puede usar `resample(frecuencia)[columna]`. 

Las frecuencias que puede usar son:
* H - Horaria
* D - Diaria
* W - Semanal
* M - Mensual
* A - Anual

Puede usar `.agg([columnas])` para agregar los datos

### Solución

In [91]:
MA_y_ME_data= data.resample('W')['artist'].agg(['first','last'])

In [96]:
MA_y_ME_data.columns=(['mas_esc','menos_esc'])

In [97]:
MA_y_ME_data

                                  mas_esc                   menos_esc
date
1958-08-10                   Ricky Nelson             Frankie Vaughan
1958-08-17                   Ricky Nelson        The Kirby Stone Four
1958-08-24               Domenico Modugno     Count Basie & His Orch.
1958-08-31                   The Elegants              Eileen Rodgers
1958-09-07               Domenico Modugno                  Jill Corey
...                                   ...                         ...
2021-10-10                 Coldplay x BTS                  Kanye West
2021-10-17  The Kid LAROI & Justin Bieber  YoungBoy Never Broke Again
2021-10-24        Lil Nas X & Jack Harlow  YoungBoy Never Broke Again
2021-10-31                          Adele             Priscilla Block
2021-11-07                          Adele  YoungBoy Never Broke Again

[3301 rows x 2 columns]